# Create **`Dockerfile.single`** that:
# - uses `node:20`
# - installs dependencies
# - builds the app
# - starts with `npm run start`
# - **must work** at `http://localhost:3000/health`
FROM  node:20
WORKDIR /app
COPY package.json .
RUN npm install 
COPY . .
RUN npm run build
EXPOSE 3000
CMD [ "npm","start" ]