apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe
        image: nginx
        resources:
          limits:
            cpu: "500m"     
            memory: "500Mi"
        ports:
          - containerPort: 80
        volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
      volumes:   
      - name: html-volume
        configMap:
          name: fe-config
          items:
            - key: index.html
              path: index.html
