apiVersion: v1
kind: Pod
metadata:
  name: scenario3
spec:
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"
  containers:
  - name: scenario3
    image: httpd

