apiVersion: v1
kind: Pod
metadata:
  name: scenario2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd
  containers:
  - name: scenario2
    image: busybox